### PR TITLE
feat: add storybook override

### LINKED ISSUE #243: add storybook override
see https://github.com/silx-kit/h5web/blob/master/.eslintrc.js#L87

### PR DESCRIPTION
**Pull request by ljosberinn**
closes #243

based on https://github.com/silx-kit/h5web/blob/main/.eslintrc.js#L87

### CODE REVIEW

**Comment by ljosberinn** [comment]
hi @axelboc - would you mind reviewing this if you find the time? I don't personally use storybook at the moment; will in the future though and would like to get some eyes on this upfront :)

**Review by TheMaru — APPROVED** [review]
Looks good to me, I don't have any other storybook overrides in my projects as well

**Comment by axelboc** [comment]
Awesome!

I've linked this branch in my project, but for some reason, I'm still getting warnings for `react/function-component-definition` :shrug: (The `import/no-anonymous-default-export` errors do go away, though). Perhaps an ordering issue?

**Comment by ljosberinn** [comment]
Hm yes I can see why I think, that was the last thing I still had to try. Currently the React override comes after the Storybook override, and thus `react/*` rules take priority for `*.(js|ts)?(x)` files which includes Storybook. I'll change the order later today!

**Review by axelboc — APPROVED** [review]

**Pull request merged**
